version: "3.9"
services:
  rails:
    build: .
    container_name: blog_web
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - rails
